-- Создание таблицы Souvenirs
CREATE TABLE Souvenirs (
    ID BIGINT PRIMARY KEY,
    URL VARCHAR(100) NOT NULL,
    ShortName VARCHAR(150) NOT NULL,
    Name VARCHAR(200) NOT NULL,
    Description VARCHAR(2500) NOT NULL,
    Rating SMALLINT NOT NULL,
    IdCategory BIGINT NOT NULL,
    IdColor BIGINT NOT NULL,
    Size VARCHAR(150) NOT NULL,
    IdMaterial INT NOT NULL,
    Weight DECIMAL(10,3),
    QTypics VARCHAR(10),
    PicsSize VARCHAR(20),
    IdApplicMethod INT NOT NULL,
    AllCategories VARCHAR(150) NOT NULL,
    DealerPrice DECIMAL(10,2) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Comments VARCHAR(1000),
    FOREIGN KEY (IdCategory) REFERENCES SouvenirCategories(ID),
    FOREIGN KEY (IdColor) REFERENCES Colors(ID),
    FOREIGN KEY (IdMaterial) REFERENCES SouvenirMaterials(ID),
    FOREIGN KEY (IdApplicMethod) REFERENCES ApplicationMethods(ID)
);